-- Table: public.patient

-- DROP TABLE IF EXISTS public.patient;

CREATE TABLE IF NOT EXISTS public.patient
(
    "PatientRecordNumber" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "Firstname" character varying COLLATE pg_catalog."default",
    "Lastname" character varying COLLATE pg_catalog."default",
    "SSN" character varying COLLATE pg_catalog."default" NOT NULL,
    "DOB" date NOT NULL,
    "Gender" character varying COLLATE pg_catalog."default",
    "Address" character varying COLLATE pg_catalog."default",
    "PhysicianID" bigint NOT NULL,
    insuranceid bigint,
    CONSTRAINT patient_pkey PRIMARY KEY ("PatientRecordNumber"),
    CONSTRAINT "patient_PhysicianID_fkey" FOREIGN KEY ("PhysicianID")
        REFERENCES public.physician ("PhysicianID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.patient
    OWNER to postgres;