-- Table: public.physician

-- DROP TABLE IF EXISTS public.physician;

CREATE TABLE IF NOT EXISTS public.physician
(
    "PhysicianID" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "FirstName" character varying COLLATE pg_catalog."default",
    "LastName" character varying COLLATE pg_catalog."default",
    "Title" character varying COLLATE pg_catalog."default",
    "SSN" integer NOT NULL,
    CONSTRAINT physician_pkey PRIMARY KEY ("PhysicianID")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.physician
    OWNER to postgres;