-- Table: public.appointments

-- DROP TABLE IF EXISTS public.appointments;

CREATE TABLE IF NOT EXISTS public.appointments
(
    "AppointmentID" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "PatientRecordNumber" bigint NOT NULL,
    "NurseID" bigint NOT NULL,
    "PhysicianID" bigint NOT NULL,
    "StartDateTime" timestamp with time zone NOT NULL,
    "EndDateTime" timestamp with time zone NOT NULL,
    "ExamRoomID" integer NOT NULL,
    CONSTRAINT appointments_pkey PRIMARY KEY ("AppointmentID"),
    CONSTRAINT "appointments_ExamRoomID_fkey" FOREIGN KEY ("ExamRoomID")
        REFERENCES public.room ("ExamRoomID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "appointments_PatientRecordNumber_fkey" FOREIGN KEY ("PatientRecordNumber")
        REFERENCES public.patient ("PatientRecordNumber") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "appointments_PhysicianID_fkey" FOREIGN KEY ("PhysicianID")
        REFERENCES public.physician ("PhysicianID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.appointments
    OWNER to postgres;